// 中英文分类映射（供内容中心下拉筛选与结果卡片共用）

import { t as $t } from "../i18n";
// Modrinth slug → 中文
export const CN_CATS: Record<string, string> = {
  fabric: "Fabric",
  forge: "Forge",
  neoforge: "NeoForge",
  quilt: "Quilt",
  optimization: $t("utils.categories.512x"),
  library: $t("utils.categories.fabric"),
  utility: $t("utils.categories.pv-p"),
  adventure: $t("utils.categories.16x"),
  magic: $t("utils.categories.32x"),
  tech: $t("utils.categories.64x"),
  decoration: $t("utils.categories.128x"),
  equipment: $t("utils.categories.256x"),
  food: $t("utils.categories.faithful"),
  misc: $t("utils.categories.cursed"),
  mobs: $t("utils.categories.3-d"),
  storage: $t("utils.categories.storage"),
  worldgen: $t("utils.categories.hud"),
  challenge: $t("utils.categories.forge"),
  combat: $t("utils.categories.neo-forge"),
  hardcore: $t("utils.categories.pbr"),
  "mini-game": $t("utils.categories.pv-e"),
  multiplayer: $t("utils.categories.quilt"),
  pvp: "PvP",
  "vanilla-plus": $t("utils.categories.complementary"),
  "16x": "16x",
  "32x": "32x",
  "64x": "64x",
  "128x": "128x",
  "256x": "256x",
  "512x": "512x",
  faithful: "Faithful",
  cursed: "Cursed",
  modern: $t("utils.categories.modern"),
  "semi-realistic": $t("utils.categories.semi-realistic"),
  simplistic: $t("utils.categories.48x"),
  themed: $t("common.theme"),
  potato: $t("utils.categories.8x"),
  low: $t("utils.categories.mmo"),
  medium: $t("utils.categories.op"),
  high: $t("utils.categories.rpg"),
  ultra: $t("utils.categories.ultra"),
  "path-tracing": $t("utils.categories.path-tracing"),
  complementary: "Complementary",
  realistic: $t("utils.categories.smp"),
  // 更多 Modrinth 分类
  armor: $t("utils.categories.armor"),
  atmosphere: $t("utils.categories.atmosphere"),
  cosmetic: $t("utils.categories.cosmetic"),
  difficulty: $t("utils.categories.difficulty"),
  economy: $t("utils.categories.economy"),
  "game-mechanics": $t("utils.categories.game-mechanics"),
  gameplay: $t("utils.categories.group"),
  management: $t("common.manage"),
  performance: $t("utils.categories.int"),
  physics: $t("utils.categories.physics"),
  redstone: $t("utils.categories.redstone"),
  "server-utility": $t("utils.categories.server-utility"),
  social: $t("utils.categories.social"),
  technology: $t("utils.categories.64x"),
  tweaks: $t("utils.categories.tweaks"),
  translation: $t("utils.categories.translation"),
  locale: $t("utils.categories.translation"),
  animated: $t("utils.categories.animated"),
  model: $t("utils.categories.model"),
  entity: $t("utils.categories.entity"),
  gui: $t("utils.categories.gui"),
  font: $t("utils.categories.font"),
  "3d": "3D",
  hud: "HUD",
  texture: $t("utils.categories.texture"),
  traditional: $t("utils.categories.traditional"),
  cartoon: $t("utils.categories.cartoon"),
  photorealism: $t("utils.categories.smp"),
  vanilla: $t("utils.categories.vanilla"),
  simple: $t("utils.categories.48x"),
  ancient: $t("utils.categories.ancient"),
  fancy: $t("utils.categories.fancy"),
  medieval: $t("utils.categories.medieval"),
  blend: $t("utils.categories.blend"),
  connect: $t("utils.categories.connect"),
  tileable: $t("utils.categories.tileable"),
  fantasy: $t("utils.categories.fantasy"),
  nostalgic: $t("utils.categories.nostalgic"),
  "48x": "48x",
  "512x+": "512x+",
  "8x-": "8x-",
  "adventure-mode": $t("utils.categories.adventure-mode"),
  anarchy: $t("utils.categories.anarchy"),
  audio: $t("utils.categories.audio"),
  "battle-royale": $t("utils.categories.battle-royale"),
  bedwars: $t("utils.categories.bedwars"),
  blocks: $t("utils.categories.blocks"),
  bloom: $t("utils.categories.bloom"),
  bosses: $t("utils.categories.bosses"),
  challenging: $t("utils.categories.forge"),
  classes: $t("utils.categories.classes"),
  "colored-lighting": $t("utils.categories.colored-lighting"),
  competitive: $t("utils.categories.competitive"),
  "core-shaders": $t("utils.categories.core-shaders"),
  "creative-mode": $t("utils.categories.creative-mode"),
  "creator-community": $t("utils.categories.creator-community"),
  crossplay: $t("utils.categories.crossplay"),
  "custom-content": $t("utils.categories.custom-content"),
  dungeons: $t("utils.categories.dungeons"),
  entities: $t("utils.categories.entity"),
  environment: $t("utils.categories.environment"),
  factions: $t("utils.categories.factions"),
  foliage: $t("utils.categories.foliage"),
  fonts: $t("utils.categories.font"),
  gens: $t("utils.categories.gens"),
  "hardcore-mode": $t("utils.categories.hardcore-mode"),
  items: $t("utils.categories.items"),
  "keep-inventory": $t("utils.categories.keep-inventory"),
  "kitchen-sink": $t("utils.categories.kitchen-sink"),
  kitpvp: $t("utils.categories.kitpvp"),
  lifesteal: $t("utils.categories.lifesteal"),
  lightweight: $t("utils.categories.lightweight"),
  media: $t("utils.categories.media"),
  microgames: $t("utils.categories.microgames"),
  minigame: $t("utils.categories.pv-e"),
  minigames: $t("utils.categories.pv-e"),
  mmo: "MMO",
  modded: $t("utils.categories.modded"),
  models: $t("utils.categories.model"),
  network: $t("utils.categories.network"),
  "offline-mode": $t("utils.categories.offline-mode"),
  oneblock: $t("utils.categories.oneblock"),
  op: "OP",
  parkour: $t("utils.categories.parkour"),
  pbr: "PBR",
  "personal-worlds": $t("utils.categories.personal-worlds"),
  plots: $t("utils.categories.plots"),
  pokemon: $t("utils.categories.pokemon"),
  prison: $t("utils.categories.prison"),
  pve: "PvE",
  questing: $t("utils.categories.questing"),
  quests: $t("utils.categories.questing"),
  racing: $t("utils.categories.racing"),
  "recording-smp": $t("utils.categories.recording-smp"),
  reflections: $t("utils.categories.reflections"),
  roleplay: $t("utils.categories.roleplay"),
  rpg: "RPG",
  screenshot: $t("utils.categories.screenshot"),
  shadows: $t("utils.categories.shadows"),
  skyblock: $t("utils.categories.skyblock"),
  smp: "SMP",
  teams: $t("utils.categories.teams"),
  technical: $t("utils.categories.technical"),
  towns: $t("utils.categories.towns"),
  transportation: $t("utils.categories.transportation"),
  "vanilla-like": $t("utils.categories.vanilla-like"),
  whitelisted: $t("utils.categories.whitelisted"),
  "world-resets": $t("utils.categories.world-resets"),
};

// CurseForge 英文分类名 → 中文
export const CN_CF_CATS: Record<string, string> = {
  adventure: $t("utils.categories.16x"),
  "adventure and rpg": $t("utils.categories.mcreator"),
  "adventure and exploration": $t("utils.categories.1024x"),
  "challenge and exploration": $t("utils.categories.challenge-and-exploration"),
  magic: $t("utils.categories.32x"),
  tech: $t("utils.categories.64x"),
  decoration: $t("utils.categories.128x"),
  equipment: $t("utils.categories.256x"),
  food: $t("utils.categories.faithful"),
  misc: $t("utils.categories.cursed"),
  mobs: $t("utils.categories.3-d"),
  storage: $t("utils.categories.storage"),
  worldgen: $t("utils.categories.hud"),
  "world generation": $t("utils.categories.hud"),
  "api and library": $t("utils.categories.api-and-library"),
  "abstraction library": $t("utils.categories.abstraction-library"),
  library: $t("utils.categories.api-and-library"),
  optimization: $t("utils.categories.512x"),
  performance: $t("utils.categories.performance"),
  "server utility": $t("utils.categories.server-utility"),
  utility: $t("utils.categories.pv-p"),
  "utility and quality of life": $t("utils.categories.utility-and-quality-of-life"),
  "armor, tools, and weapons": $t("utils.categories.armor-tools-and-weapons"),
  "astral sorcery": $t("utils.categories.astral-sorcery"),
  "audio, video": $t("utils.categories.audio-video"),
  biomes: $t("utils.categories.biomes"),
  "blood magic": $t("utils.categories.blood-magic"),
  botany: $t("utils.categories.botany"),
  buildcraft: $t("utils.categories.buildcraft"),
  chemistry: $t("utils.categories.chemistry"),
  cooking: $t("utils.categories.cooking"),
  cosmetics: $t("utils.categories.cosmetic"),
  dimensions: $t("utils.categories.dimensions"),
  energy: $t("utils.categories.energy"),
  "farming and food": $t("utils.categories.farming-and-food"),
  forestry: $t("utils.categories.forestry"),
  genetics: $t("utils.categories.genetics"),
  horses: $t("utils.categories.horses"),
  "industrial craft": $t("utils.categories.industrial-craft"),
  mcreator: "MCreator",
  redstone: $t("utils.categories.redstone"),
  thaumcraft: $t("utils.categories.thaumcraft"),
  "tinker's construct": $t("utils.categories.tinker-s-construct"),
  transport: $t("utils.categories.transport"),
  tweaks: $t("utils.categories.tweaks"),
  "world gen": $t("utils.categories.hud"),
  miscellaneous: $t("utils.categories.cursed"),
  addons: $t("utils.categories.addons"),
  capes: $t("utils.categories.capes"),
  customization: $t("instance-settings.mcreator"),
  "game mechanic": $t("utils.categories.game-mechanics"),
  "map and information": $t("utils.categories.map-and-information"),
  social: $t("utils.categories.social"),
  "combat and pvp": $t("utils.categories.combat-and-pvp"),
  hardcore: $t("utils.categories.pbr"),
  minigame: $t("utils.categories.pv-e"),
  pve: "PvE",
  pvp: "PvP",
  "quality of life": $t("utils.categories.quality-of-life"),
  roleplaying: $t("utils.categories.roleplay"),
  "simple and clean": $t("utils.categories.simple-and-clean"),
  themed: $t("common.theme"),
  "photo realistic": $t("utils.categories.photo-realistic"),
  "semi-realistic": $t("utils.categories.semi-realistic"),
  cartoon: $t("utils.categories.cartoon"),
  "sci-fi": $t("utils.categories.sci-fi"),
  medieval: $t("utils.categories.medieval"),
  modern: $t("utils.categories.modern"),
  anime: $t("utils.categories.anime"),
  cursed: "Cursed",
  faithful: "Faithful",
  "high resolution": $t("utils.categories.high-resolution"),
  "low resolution": $t("utils.categories.low-resolution"),
  pbr: "PBR",
  "potato graphics": $t("utils.categories.8x"),
  shader: $t("utils.categories.shader"),
  // 更多 CurseForge 分类（含分辨率的英文叫法）
  sixteen: "16x",
  "thirty two": "32x",
  "sixty four": "64x",
  "one hundred twenty eight": "128x",
  "two hundred fifty six": "256x",
  "five hundred twelve": "512x",
  "one thousand twenty four": "1024x",
  traditional: $t("utils.categories.traditional"),
  theme: $t("common.theme"),
  simple: $t("utils.categories.48x"),
  gui: $t("utils.categories.gui"),
  font: $t("utils.categories.font"),
  hud: "HUD",
  "3d": "3D",
  animated: $t("utils.categories.animated"),
  model: $t("utils.categories.model"),
  entity: $t("utils.categories.entity"),
  compatibility: $t("utils.categories.compatibility"),
  compat: $t("utils.categories.compatibility"),
  bugfix: $t("utils.categories.bugfix"),
  weapon: $t("utils.categories.weapon"),
  armor: $t("utils.categories.armor"),
  "one-click": $t("install-dialog.mcreator"),
  skybox: $t("utils.categories.skybox"),
  "mini game": $t("utils.categories.pv-e"),
  "full hd": $t("utils.categories.full-hd"),
  "game-like": $t("utils.categories.game-like"),
  fog: $t("utils.categories.fog"),
  solid: $t("utils.categories.solid"),
  movie: $t("utils.categories.movie"),
  "path tracing": $t("utils.categories.path-tracing"),
  ultra: $t("utils.categories.ultra"),
  "colored lighting": $t("utils.categories.colored-lighting"),
  "clean and simple": $t("utils.categories.simple-and-clean"),
  lightweight: $t("utils.categories.lightweight"),
};

/** CurseForge 英文分类名 → 中文（未命中回退原名） */
export function cnCfName(name: string): string {
  return CN_CF_CATS[name.toLowerCase()] ?? name;
}

/** 通用分类翻译：Modrinth slug / CurseForge 英文名 → 中文（未命中回退原值） */
export function translateCategory(c: string): string {
  if (!c) return c;
  return CN_CATS[c] ?? CN_CF_CATS[c.toLowerCase()] ?? c;
}
